// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package api is a generated GoMock package.
package api

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	advert_proto "github.com/s21platform/advert-proto/advert-proto"
	avatar "github.com/s21platform/avatar-service/pkg/avatar"
	chat "github.com/s21platform/chat-service/pkg/chat"
	feed_proto "github.com/s21platform/feed-proto/feed-proto"
	model "github.com/s21platform/gateway-service/internal/model"
	notification "github.com/s21platform/notification-service/pkg/notification"
	optionhub_proto "github.com/s21platform/optionhub-proto/optionhub-proto"
	society_proto "github.com/s21platform/society-proto/society-proto"
	user "github.com/s21platform/user-service/pkg/user"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetInfoByUUID mocks base method.
func (m *MockUserService) GetInfoByUUID(r *http.Request) (*user.GetUserInfoByUUIDOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfoByUUID", r)
	ret0, _ := ret[0].(*user.GetUserInfoByUUIDOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfoByUUID indicates an expected call of GetInfoByUUID.
func (mr *MockUserServiceMockRecorder) GetInfoByUUID(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfoByUUID", reflect.TypeOf((*MockUserService)(nil).GetInfoByUUID), r)
}

// GetPeerInfo mocks base method.
func (m *MockUserService) GetPeerInfo(r *http.Request) (*user.GetUserInfoByUUIDOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerInfo", r)
	ret0, _ := ret[0].(*user.GetUserInfoByUUIDOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerInfo indicates an expected call of GetPeerInfo.
func (mr *MockUserServiceMockRecorder) GetPeerInfo(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerInfo", reflect.TypeOf((*MockUserService)(nil).GetPeerInfo), r)
}

// GetUserCountFriends mocks base method.
func (m *MockUserService) GetUserCountFriends(r *http.Request) (*user.GetCountFriendsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCountFriends", r)
	ret0, _ := ret[0].(*user.GetCountFriendsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCountFriends indicates an expected call of GetUserCountFriends.
func (mr *MockUserServiceMockRecorder) GetUserCountFriends(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCountFriends", reflect.TypeOf((*MockUserService)(nil).GetUserCountFriends), r)
}

// RemoveUserFriends mocks base method.
func (m *MockUserService) RemoveUserFriends(r *http.Request) (*user.RemoveFriendsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFriends", r)
	ret0, _ := ret[0].(*user.RemoveFriendsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUserFriends indicates an expected call of RemoveUserFriends.
func (mr *MockUserServiceMockRecorder) RemoveUserFriends(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFriends", reflect.TypeOf((*MockUserService)(nil).RemoveUserFriends), r)
}

// SetUserFriends mocks base method.
func (m *MockUserService) SetUserFriends(r *http.Request) (*user.SetFriendsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserFriends", r)
	ret0, _ := ret[0].(*user.SetFriendsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserFriends indicates an expected call of SetUserFriends.
func (mr *MockUserServiceMockRecorder) SetUserFriends(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserFriends", reflect.TypeOf((*MockUserService)(nil).SetUserFriends), r)
}

// UpdateProfileInfo mocks base method.
func (m *MockUserService) UpdateProfileInfo(r *http.Request) (*user.UpdateProfileOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileInfo", r)
	ret0, _ := ret[0].(*user.UpdateProfileOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileInfo indicates an expected call of UpdateProfileInfo.
func (mr *MockUserServiceMockRecorder) UpdateProfileInfo(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileInfo", reflect.TypeOf((*MockUserService)(nil).UpdateProfileInfo), r)
}

// MockAvatarService is a mock of AvatarService interface.
type MockAvatarService struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarServiceMockRecorder
}

// MockAvatarServiceMockRecorder is the mock recorder for MockAvatarService.
type MockAvatarServiceMockRecorder struct {
	mock *MockAvatarService
}

// NewMockAvatarService creates a new mock instance.
func NewMockAvatarService(ctrl *gomock.Controller) *MockAvatarService {
	mock := &MockAvatarService{ctrl: ctrl}
	mock.recorder = &MockAvatarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarService) EXPECT() *MockAvatarServiceMockRecorder {
	return m.recorder
}

// GetSocietyAvatarsList mocks base method.
func (m *MockAvatarService) GetSocietyAvatarsList(r *http.Request) (*avatar.GetAllSocietyAvatarsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocietyAvatarsList", r)
	ret0, _ := ret[0].(*avatar.GetAllSocietyAvatarsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSocietyAvatarsList indicates an expected call of GetSocietyAvatarsList.
func (mr *MockAvatarServiceMockRecorder) GetSocietyAvatarsList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocietyAvatarsList", reflect.TypeOf((*MockAvatarService)(nil).GetSocietyAvatarsList), r)
}

// GetUserAvatarsList mocks base method.
func (m *MockAvatarService) GetUserAvatarsList(r *http.Request) (*avatar.GetAllUserAvatarsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatarsList", r)
	ret0, _ := ret[0].(*avatar.GetAllUserAvatarsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAvatarsList indicates an expected call of GetUserAvatarsList.
func (mr *MockAvatarServiceMockRecorder) GetUserAvatarsList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatarsList", reflect.TypeOf((*MockAvatarService)(nil).GetUserAvatarsList), r)
}

// RemoveSocietyAvatar mocks base method.
func (m *MockAvatarService) RemoveSocietyAvatar(r *http.Request) (*avatar.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSocietyAvatar", r)
	ret0, _ := ret[0].(*avatar.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveSocietyAvatar indicates an expected call of RemoveSocietyAvatar.
func (mr *MockAvatarServiceMockRecorder) RemoveSocietyAvatar(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSocietyAvatar", reflect.TypeOf((*MockAvatarService)(nil).RemoveSocietyAvatar), r)
}

// RemoveUserAvatar mocks base method.
func (m *MockAvatarService) RemoveUserAvatar(r *http.Request) (*avatar.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserAvatar", r)
	ret0, _ := ret[0].(*avatar.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUserAvatar indicates an expected call of RemoveUserAvatar.
func (mr *MockAvatarServiceMockRecorder) RemoveUserAvatar(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserAvatar", reflect.TypeOf((*MockAvatarService)(nil).RemoveUserAvatar), r)
}

// UploadSocietyAvatar mocks base method.
func (m *MockAvatarService) UploadSocietyAvatar(r *http.Request) (*avatar.SetSocietyAvatarOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSocietyAvatar", r)
	ret0, _ := ret[0].(*avatar.SetSocietyAvatarOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSocietyAvatar indicates an expected call of UploadSocietyAvatar.
func (mr *MockAvatarServiceMockRecorder) UploadSocietyAvatar(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSocietyAvatar", reflect.TypeOf((*MockAvatarService)(nil).UploadSocietyAvatar), r)
}

// UploadUserAvatar mocks base method.
func (m *MockAvatarService) UploadUserAvatar(r *http.Request) (*avatar.SetUserAvatarOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadUserAvatar", r)
	ret0, _ := ret[0].(*avatar.SetUserAvatarOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadUserAvatar indicates an expected call of UploadUserAvatar.
func (mr *MockAvatarServiceMockRecorder) UploadUserAvatar(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadUserAvatar", reflect.TypeOf((*MockAvatarService)(nil).UploadUserAvatar), r)
}

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// GetCountNotification mocks base method.
func (m *MockNotificationService) GetCountNotification(r *http.Request) (*notification.NotificationCountOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountNotification", r)
	ret0, _ := ret[0].(*notification.NotificationCountOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountNotification indicates an expected call of GetCountNotification.
func (mr *MockNotificationServiceMockRecorder) GetCountNotification(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountNotification", reflect.TypeOf((*MockNotificationService)(nil).GetCountNotification), r)
}

// GetNotification mocks base method.
func (m *MockNotificationService) GetNotification(r *http.Request) (*notification.NotificationOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotification", r)
	ret0, _ := ret[0].(*notification.NotificationOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotification indicates an expected call of GetNotification.
func (mr *MockNotificationServiceMockRecorder) GetNotification(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotification", reflect.TypeOf((*MockNotificationService)(nil).GetNotification), r)
}

// MarkNotificationsAsRead mocks base method.
func (m *MockNotificationService) MarkNotificationsAsRead(r *http.Request) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationsAsRead", r)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationsAsRead indicates an expected call of MarkNotificationsAsRead.
func (mr *MockNotificationServiceMockRecorder) MarkNotificationsAsRead(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationsAsRead", reflect.TypeOf((*MockNotificationService)(nil).MarkNotificationsAsRead), r)
}

// MockOptionService is a mock of OptionService interface.
type MockOptionService struct {
	ctrl     *gomock.Controller
	recorder *MockOptionServiceMockRecorder
}

// MockOptionServiceMockRecorder is the mock recorder for MockOptionService.
type MockOptionServiceMockRecorder struct {
	mock *MockOptionService
}

// NewMockOptionService creates a new mock instance.
func NewMockOptionService(ctrl *gomock.Controller) *MockOptionService {
	mock := &MockOptionService{ctrl: ctrl}
	mock.recorder = &MockOptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOptionService) EXPECT() *MockOptionServiceMockRecorder {
	return m.recorder
}

// GetCityList mocks base method.
func (m *MockOptionService) GetCityList(r *http.Request) (*optionhub_proto.GetByNameOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityList", r)
	ret0, _ := ret[0].(*optionhub_proto.GetByNameOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityList indicates an expected call of GetCityList.
func (mr *MockOptionServiceMockRecorder) GetCityList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityList", reflect.TypeOf((*MockOptionService)(nil).GetCityList), r)
}

// GetHobbyList mocks base method.
func (m *MockOptionService) GetHobbyList(r *http.Request) (*optionhub_proto.GetByNameOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHobbyList", r)
	ret0, _ := ret[0].(*optionhub_proto.GetByNameOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHobbyList indicates an expected call of GetHobbyList.
func (mr *MockOptionServiceMockRecorder) GetHobbyList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHobbyList", reflect.TypeOf((*MockOptionService)(nil).GetHobbyList), r)
}

// GetOptionRequests mocks base method.
func (m *MockOptionService) GetOptionRequests(r *http.Request) (model.OptionRequestsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptionRequests", r)
	ret0, _ := ret[0].(model.OptionRequestsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptionRequests indicates an expected call of GetOptionRequests.
func (mr *MockOptionServiceMockRecorder) GetOptionRequests(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptionRequests", reflect.TypeOf((*MockOptionService)(nil).GetOptionRequests), r)
}

// GetOsList mocks base method.
func (m *MockOptionService) GetOsList(r *http.Request) (*model.OptionsStruct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOsList", r)
	ret0, _ := ret[0].(*model.OptionsStruct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOsList indicates an expected call of GetOsList.
func (mr *MockOptionServiceMockRecorder) GetOsList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOsList", reflect.TypeOf((*MockOptionService)(nil).GetOsList), r)
}

// GetSkillList mocks base method.
func (m *MockOptionService) GetSkillList(r *http.Request) (*optionhub_proto.GetByNameOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillList", r)
	ret0, _ := ret[0].(*optionhub_proto.GetByNameOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillList indicates an expected call of GetSkillList.
func (mr *MockOptionServiceMockRecorder) GetSkillList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillList", reflect.TypeOf((*MockOptionService)(nil).GetSkillList), r)
}

// GetSocietyDirectionList mocks base method.
func (m *MockOptionService) GetSocietyDirectionList(r *http.Request) (*optionhub_proto.GetByNameOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocietyDirectionList", r)
	ret0, _ := ret[0].(*optionhub_proto.GetByNameOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSocietyDirectionList indicates an expected call of GetSocietyDirectionList.
func (mr *MockOptionServiceMockRecorder) GetSocietyDirectionList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocietyDirectionList", reflect.TypeOf((*MockOptionService)(nil).GetSocietyDirectionList), r)
}

// GetStudyPlaceList mocks base method.
func (m *MockOptionService) GetStudyPlaceList(r *http.Request) (*optionhub_proto.GetByNameOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyPlaceList", r)
	ret0, _ := ret[0].(*optionhub_proto.GetByNameOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyPlaceList indicates an expected call of GetStudyPlaceList.
func (mr *MockOptionServiceMockRecorder) GetStudyPlaceList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyPlaceList", reflect.TypeOf((*MockOptionService)(nil).GetStudyPlaceList), r)
}

// GetWorkPlaceList mocks base method.
func (m *MockOptionService) GetWorkPlaceList(r *http.Request) (*optionhub_proto.GetByNameOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkPlaceList", r)
	ret0, _ := ret[0].(*optionhub_proto.GetByNameOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkPlaceList indicates an expected call of GetWorkPlaceList.
func (mr *MockOptionServiceMockRecorder) GetWorkPlaceList(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkPlaceList", reflect.TypeOf((*MockOptionService)(nil).GetWorkPlaceList), r)
}

// MockSocietyService is a mock of SocietyService interface.
type MockSocietyService struct {
	ctrl     *gomock.Controller
	recorder *MockSocietyServiceMockRecorder
}

// MockSocietyServiceMockRecorder is the mock recorder for MockSocietyService.
type MockSocietyServiceMockRecorder struct {
	mock *MockSocietyService
}

// NewMockSocietyService creates a new mock instance.
func NewMockSocietyService(ctrl *gomock.Controller) *MockSocietyService {
	mock := &MockSocietyService{ctrl: ctrl}
	mock.recorder = &MockSocietyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocietyService) EXPECT() *MockSocietyServiceMockRecorder {
	return m.recorder
}

// CreateSociety mocks base method.
func (m *MockSocietyService) CreateSociety(r *http.Request) (*society_proto.SetSocietyOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSociety", r)
	ret0, _ := ret[0].(*society_proto.SetSocietyOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSociety indicates an expected call of CreateSociety.
func (mr *MockSocietyServiceMockRecorder) CreateSociety(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSociety", reflect.TypeOf((*MockSocietyService)(nil).CreateSociety), r)
}

// GetSocietyInfo mocks base method.
func (m *MockSocietyService) GetSocietyInfo(r *http.Request) (*model.SocietyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocietyInfo", r)
	ret0, _ := ret[0].(*model.SocietyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSocietyInfo indicates an expected call of GetSocietyInfo.
func (mr *MockSocietyServiceMockRecorder) GetSocietyInfo(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocietyInfo", reflect.TypeOf((*MockSocietyService)(nil).GetSocietyInfo), r)
}

// UpdateSociety mocks base method.
func (m *MockSocietyService) UpdateSociety(r *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSociety", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSociety indicates an expected call of UpdateSociety.
func (mr *MockSocietyServiceMockRecorder) UpdateSociety(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSociety", reflect.TypeOf((*MockSocietyService)(nil).UpdateSociety), r)
}

// MockSearchService is a mock of SearchService interface.
type MockSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceMockRecorder
}

// MockSearchServiceMockRecorder is the mock recorder for MockSearchService.
type MockSearchServiceMockRecorder struct {
	mock *MockSearchService
}

// NewMockSearchService creates a new mock instance.
func NewMockSearchService(ctrl *gomock.Controller) *MockSearchService {
	mock := &MockSearchService{ctrl: ctrl}
	mock.recorder = &MockSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchService) EXPECT() *MockSearchServiceMockRecorder {
	return m.recorder
}

// GetSocietyWithLimit mocks base method.
func (m *MockSearchService) GetSocietyWithLimit(r *http.Request) (model.SearchSocietyOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocietyWithLimit", r)
	ret0, _ := ret[0].(model.SearchSocietyOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSocietyWithLimit indicates an expected call of GetSocietyWithLimit.
func (mr *MockSearchServiceMockRecorder) GetSocietyWithLimit(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocietyWithLimit", reflect.TypeOf((*MockSearchService)(nil).GetSocietyWithLimit), r)
}

// GetUsersWithLimit mocks base method.
func (m *MockSearchService) GetUsersWithLimit(r *http.Request) (model.SearchUsersOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersWithLimit", r)
	ret0, _ := ret[0].(model.SearchUsersOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersWithLimit indicates an expected call of GetUsersWithLimit.
func (mr *MockSearchServiceMockRecorder) GetUsersWithLimit(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersWithLimit", reflect.TypeOf((*MockSearchService)(nil).GetUsersWithLimit), r)
}

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// CreatePrivateChat mocks base method.
func (m *MockChatService) CreatePrivateChat(r *http.Request) (*chat.CreatePrivateChatOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateChat", r)
	ret0, _ := ret[0].(*chat.CreatePrivateChatOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateChat indicates an expected call of CreatePrivateChat.
func (mr *MockChatServiceMockRecorder) CreatePrivateChat(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateChat", reflect.TypeOf((*MockChatService)(nil).CreatePrivateChat), r)
}

// GetChats mocks base method.
func (m *MockChatService) GetChats(r *http.Request) (*chat.GetChatsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChats", r)
	ret0, _ := ret[0].(*chat.GetChatsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChats indicates an expected call of GetChats.
func (mr *MockChatServiceMockRecorder) GetChats(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChats", reflect.TypeOf((*MockChatService)(nil).GetChats), r)
}

// GetPrivateRecentMessages mocks base method.
func (m *MockChatService) GetPrivateRecentMessages(r *http.Request) (*chat.GetPrivateRecentMessagesOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateRecentMessages", r)
	ret0, _ := ret[0].(*chat.GetPrivateRecentMessagesOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateRecentMessages indicates an expected call of GetPrivateRecentMessages.
func (mr *MockChatServiceMockRecorder) GetPrivateRecentMessages(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateRecentMessages", reflect.TypeOf((*MockChatService)(nil).GetPrivateRecentMessages), r)
}

// MockAdvertService is a mock of AdvertService interface.
type MockAdvertService struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertServiceMockRecorder
}

// MockAdvertServiceMockRecorder is the mock recorder for MockAdvertService.
type MockAdvertServiceMockRecorder struct {
	mock *MockAdvertService
}

// NewMockAdvertService creates a new mock instance.
func NewMockAdvertService(ctrl *gomock.Controller) *MockAdvertService {
	mock := &MockAdvertService{ctrl: ctrl}
	mock.recorder = &MockAdvertServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertService) EXPECT() *MockAdvertServiceMockRecorder {
	return m.recorder
}

// CancelAdvert mocks base method.
func (m *MockAdvertService) CancelAdvert(r *http.Request) (*advert_proto.AdvertEmpty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAdvert", r)
	ret0, _ := ret[0].(*advert_proto.AdvertEmpty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAdvert indicates an expected call of CancelAdvert.
func (mr *MockAdvertServiceMockRecorder) CancelAdvert(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAdvert", reflect.TypeOf((*MockAdvertService)(nil).CancelAdvert), r)
}

// CreateAdvert mocks base method.
func (m *MockAdvertService) CreateAdvert(r *http.Request) (*advert_proto.AdvertEmpty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdvert", r)
	ret0, _ := ret[0].(*advert_proto.AdvertEmpty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdvert indicates an expected call of CreateAdvert.
func (mr *MockAdvertServiceMockRecorder) CreateAdvert(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdvert", reflect.TypeOf((*MockAdvertService)(nil).CreateAdvert), r)
}

// GetAdverts mocks base method.
func (m *MockAdvertService) GetAdverts(r *http.Request) (*advert_proto.GetAdvertsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdverts", r)
	ret0, _ := ret[0].(*advert_proto.GetAdvertsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdverts indicates an expected call of GetAdverts.
func (mr *MockAdvertServiceMockRecorder) GetAdverts(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdverts", reflect.TypeOf((*MockAdvertService)(nil).GetAdverts), r)
}

// RestoreAdvert mocks base method.
func (m *MockAdvertService) RestoreAdvert(r *http.Request) (*advert_proto.AdvertEmpty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreAdvert", r)
	ret0, _ := ret[0].(*advert_proto.AdvertEmpty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreAdvert indicates an expected call of RestoreAdvert.
func (mr *MockAdvertServiceMockRecorder) RestoreAdvert(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreAdvert", reflect.TypeOf((*MockAdvertService)(nil).RestoreAdvert), r)
}

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// CreateUserPost mocks base method.
func (m *MockFeedService) CreateUserPost(r *http.Request) (*feed_proto.CreateUserPostOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserPost", r)
	ret0, _ := ret[0].(*feed_proto.CreateUserPostOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserPost indicates an expected call of CreateUserPost.
func (mr *MockFeedServiceMockRecorder) CreateUserPost(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserPost", reflect.TypeOf((*MockFeedService)(nil).CreateUserPost), r)
}
