name: Dev CI/CD to Development server
on:
  pull_request:
    branches:
      - 'main'


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: test work on PR
        run: echo "w"
